### ISSUE TITLE
Update init_update function signature

### ISSUE THREAD

**Issue by joakim-hove** [Statoil/libres#447]
The function signature used in analysis modules: https://github.com/Statoil/libres/blob/master/lib/include/ert/analysis/analysis_table.hpp#L46

Should get an extra argument after `ens_mask` so that the new signature becomes:

```
typedef void (analysis_init_update_ftype) (void * module_data,
                                             const bool_vector_type * ens_mask ,
                                             const bool_vector_type * obs_mask,   /* New argument */ 
                                             const matrix_type * S ,
                                             ...
```

The `obs_mask` argument should be create with `obs_data_alloc_mask()`.

**Comment by ManInFez** [comment]
Was resolved in #457
